<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li id="<?php echo $_code ?>_cpf_div">
        <label for="<?php echo $_code ?>_cpf" class="required"><em>*</em>CPF</label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cpf" name="payment[<?php echo $_code ?>_cpf]" title="<?php echo $this->__('CPF') ?>" class="input-text required-entry validate-digits" value="" />
        </div>
    </li>
</ul>