<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li style="display: none;">

        <!-- card hashes and tokens !-->
        <input type="hidden" id="<?php echo $_code ?>_pagarme_card_hash" name="payment[<?php echo $_code ?>_pagarme_card_hash]" value="" />
        <input type="hidden" id="<?php echo $_code ?>_zaaz_card_hash" name="payment[<?php echo $_code ?>_zaaz_card_hash]" value="" />
        <input type="hidden" id="<?php echo $_code ?>_zaaz_access_token" name="payment[<?php echo $_code ?>_zaaz_access_token]" value="" />

        <select id="<?php echo $_code ?>_cc_type" title="<?php echo $this->__('Credit Card Type') ?>" style="display: none;">
            <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName) : ?>
                <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
            <?php endforeach ?>
        </select>
    </li>
    <li>
        <ul class="form-list pagarme-payment-icons" id="<?php echo $_code ?>_types">
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName) : ?>
                <li class="<?php echo $_typeCode ?> on">
                    <span><?php echo $_typeName ?></span>
                </li>
            <?php endforeach ?>
        </ul>
    </li>
    <li>
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_installments" name="payment[installments]" title="<?php echo $this->__('Installments') ?>" class="required-entry validate-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_installments = $this->getInfoData('installments') ?>
                <?php foreach ($this->getInstallmentsAvailables() as $_installmentValue => $_installmentLabel) : ?>
                    <option value="<?php echo $_installmentValue ?>" <?php /* if($_installmentValue==$_installments): ?> selected="selected"<?php endif */ ?>><?php echo $_installmentLabel ?></option>
                <?php endforeach ?>
            </select>
            <input type="hidden" id="<?php echo $_code ?>_installment_description" name="payment[installment_description]" value="<?php echo $this->escapeHtml($this->getInfoData('installment_description')) ?>" />
        </div>
    </li>


    <!-- Número do cartão !-->
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" name="payment[<?php echo $_code ?>_cc_number]" class="input-text required-entry validate-cc-number" maxlength="19" value="" placeholder="•••• •••• •••• ••••" />
        </div>
    </li>


    <!-- Nome do dono do cartão !-->
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" name="payment[<?php echo $_code ?>_cc_owner]" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" value="" />
        </div>
    </li>

    <!-- CPF do dono do cartão !-->
    <li id="<?php echo $_code ?>_cpf_div">
        <label for="<?php echo $_code ?>_cpf" class="required"><em>*</em>CPF</label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cpf" name="payment[<?php echo $_code ?>_cpf]" title="<?php echo $this->__('CPF') ?>" class="input-text required-entry validate-taxvat" value="" maxlength="14" placeholder="___.___.___-__" autocomplete="off" />
        </div>
    </li>


    <!-- Mês e ano !-->
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix pagarme-cc-expr-month">
                <select id="<?php echo $_code ?>_expiration" class="month validate-pagarme-cc-exp" name="payment[<?php echo $_code ?>_expiration]">
                    <?php foreach ($this->getCcMonths() as $k => $v) : ?>
                        <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix pagarme-cc-expr-year">
                <span>/</span>
                <select id="<?php echo $_code ?>_expiration_yr" class="year" name="payment[<?php echo $_code ?>_expiration_yr]">
                    <?php foreach ($this->getCcYears() as $k => $v) : ?>
                        <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>


    <!-- CVV !-->
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix pagarme-cvv">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text pagarme-only-number cvv required-entry validate-pagarme-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[<?php echo $_code ?>_cc_cid]" maxlength="4" value="" />
                <div class="pagarme-cvv-tool-tip">
                    <img src="<?php echo $this->getSkinUrl('pagarme/images/icon_cvv.gif') ?>" class="pagarme-cvv-icon" />
                    <div class="pagarme-cvv-image"><img src="<?php echo $this->getSkinUrl('pagarme/images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                    <span class="pagarme-cvv-tool-tip-arrow">&nbsp;</span>
                </div>
            </div>
        </div>
    </li>

    <li>
        <label id="pagarme-cardhash-waiting" class="a-center" style="display:none;"><?php echo __('Just a moment ...'); ?></label>
        <label id="pagarme-cardhash-success" class="a-center" style="display:none;"><?php echo __('All right!'); ?></label>
    </li>
</ul>

<script>
    jQuery(document).ready(function() {
        const formatter = new Intl.NumberFormat('pt-BR', {
            style: 'currency',
            currency: 'BRL',
            minimumFractionDigits: 2
        })

        var subTotal = Number('<?php echo Mage::getSingleton('checkout/session')->getQuote()->getGrandTotal(); ?>');
        var juros = Number('<?php echo Mage::getStoreConfig("payment/cammino_payment_cc/installments_interest"); ?>');
        var parcelaMinima = Number('<?php echo Mage::getStoreConfig("payment/cammino_payment_cc/installments_min"); ?>');
        var parcelaNumero = 0;

        var maxInstallments = '<?php echo Mage::getStoreConfig("payment/cammino_payment_cc/installments_max"); ?>';
        var freeInstallments = '<?php echo Mage::getStoreConfig("payment/cammino_payment_cc/installments_free"); ?>';
        var arrayInstallments = Array()
        var arrayInstallmentsFree = Array()

        // Parcelas com juros
        var valueJurosSobreJuros = subTotal
        for (var i = 1; i <= maxInstallments; i++) {
            if (parcelaMinima <= (subTotal / i)) {
                if (i == 1) {
                    arrayInstallments.push({
                        'value': i,
                        'text': 'À vista - ' + formatter.format(subTotal)
                    })
                } else {
                    arrayInstallments.push({
                        'value': i,
                        'text': i + ' vezes de ' + formatter.format(valueJurosSobreJuros / i) + ' com juros.'
                    })
                }
            }
            var valueJurosSobreJuros = valueJurosSobreJuros + ((valueJurosSobreJuros / 100) * juros)
        }

        // Parcelas sem juros
        for (var i = 1; i <= maxInstallments; i++) {
            if (parcelaMinima <= (subTotal / i)) {
                if (i == 1) {
                    arrayInstallmentsFree.push({
                        'value': i,
                        'text': 'À vista - ' + formatter.format(subTotal)
                    })
                } else {
                    arrayInstallmentsFree.push({
                        'value': i,
                        'text': i + ' vezes de ' + formatter.format(subTotal / i) + ' sem juros.'
                    })
                }
            }
        }

        if (parcelaMinima > subTotal) {
            arrayInstallments.push({
                'value': 1,
                'text': 'À vista - ' + formatter.format(subTotal)
            })
            arrayInstallmentsFree.push({
                'value': 1,
                'text': 'À vista - ' + formatter.format(subTotal)
            })
        }

        var finalInstallments = Array()
        for (var i = 0; i <= maxInstallments; i++) {
            if (i <= freeInstallments) {
                finalInstallments.push(arrayInstallmentsFree[i])
            } else {
                finalInstallments.push(arrayInstallments[i])
            }
        }
        finalInstallments = finalInstallments.filter(n => n);
        console.log(finalInstallments);

        jQuery.each(finalInstallments, function(key, value) {
            jQuery('#cammino_payment_cc_installments')
                .append(jQuery("<option></option>")
                    .attr("value", value.value)
                    .text(value.text));
        });

        return finalInstallments;

    });

    jQuery('#cammino_payment_cc_cc_owner').blur(function() {
        updatePagarmeToken();
        updateZaazToken();
    });
    jQuery('#cammino_payment_cc_cc_number').blur(function() {
        updatePagarmeToken();
        updateZaazToken();
    });
    jQuery('#cammino_payment_cc_expiration').blur(function() {
        updatePagarmeToken();
        updateZaazToken();
    });
    jQuery('#cammino_payment_cc_expiration_yr').blur(function() {
        updatePagarmeToken();
        updateZaazToken();
    });
    jQuery('#cammino_payment_cc_cc_cid').blur(function() {
        updatePagarmeToken();
        updateZaazToken();
    });
    jQuery('#cammino_payment_cc_cpf').blur(function() {
        updatePagarmeToken();
        updateZaazToken();
    });

    updatePagarmeToken = function() {
        var obj = this;
        if ('<?php echo Mage::getStoreConfig("payment/cammino_payment_pagarme/active"); ?>' == '0') {
            return false;
        }
        var data = {
            type: "card",
            card: {
                holder_name: jQuery('#cammino_payment_cc_cc_owner').val() ? jQuery('#cammino_payment_cc_cc_owner').val() : null,
                number: jQuery('#cammino_payment_cc_cc_number').val() ? jQuery('#cammino_payment_cc_cc_number').val().replace(/[^A-Z0-9]+/ig, "") : null,
                exp_month: jQuery('#cammino_payment_cc_expiration').val() ? jQuery('#cammino_payment_cc_expiration').val() : null,
                exp_year: jQuery('#cammino_payment_cc_expiration_yr').val() ? jQuery('#cammino_payment_cc_expiration_yr').val() : null,
                cvv: jQuery('#cammino_payment_cc_cc_cid').val() ? jQuery('#cammino_payment_cc_cc_cid').val() : null,
                holder_document: jQuery('#cammino_payment_cc_cpf').val() ? jQuery('#cammino_payment_cc_cpf').val().replace(/[^A-Z0-9]+/ig, "") : null
            }
        }
        if ((data.card.number == null) || (data.card.cvv == null) || (data.card.exp_month == null) || (data.card.exp_year == null)) {
            return false;
        }
        if (data.card.number != null) {
            jQuery.support.cors = true;
            jQuery.ajax({
                url: 'https://api.mundipagg.com/core/v1/tokens?appId=' + '<?php echo Mage::getStoreConfig("payment/cammino_payment_pagarme/api_key"); ?>',
                header: {
                    'Content-Type': 'application/json',
                },
                type: 'POST',
                crossDomain: true,
                data: data,
                success: function(response) {
                    obj.ccToken = response.id;
                }
            });
        } else {
            obj.ccToken = false;
        }
        jQuery('#cammino_payment_cc_pagarme_card_hash').val(obj.ccToken);
    }

    updateZaazToken = function() {
        var obj = this;
        if ('<?php echo Mage::getStoreConfig("payment/cammino_payment_zaaz/active"); ?>' == '0') {
            return false;
        }
        data = {
            nomeDoCliente: jQuery('#cammino_payment_cc_cc_owner').val() ? jQuery('#cammino_payment_cc_cc_owner').val() : null,
            documento: jQuery('#cammino_payment_cc_cpf').val() ? jQuery('#cammino_payment_cc_cpf').val().replace(/[^A-Z0-9]+/ig, "") : null,
            email: null,
            celular: null,
            contato: null,
            valor: null,
            number: jQuery('#cammino_payment_cc_cc_number').val() ? jQuery('#cammino_payment_cc_cc_number').val().replace(/[^A-Z0-9]+/ig, "") : null,
            expirationMonth: jQuery('#cammino_payment_cc_expiration').val() ? jQuery('#cammino_payment_cc_expiration').val() : null,
            expirationYear: jQuery('#cammino_payment_cc_expiration_yr').val() ? jQuery('#cammino_payment_cc_expiration_yr').val() : null,
            cvv: jQuery('#cammino_payment_cc_cc_cid').val() ? jQuery('#cammino_payment_cc_cc_cid').val() : null,
            holderName: jQuery('#cammino_payment_cc_cc_owner').val() ? jQuery('#cammino_payment_cc_cc_owner').val() : null,
            quantidadeVezesRecorrencia: null,
            bandeira: getCreditCardLabel(jQuery('#cammino_payment_cc_cc_number').val().replace(/ /g,'')),
            dataCobrancaRecorrente: null
        }
        if ((data.number == null) || (data.cvv == null) || (data.expirationMonth == null) || (data.expirationYear == null)) {
            return false;
        }
        if (data.number != null) {
            jQuery.support.cors = true;
            jQuery.ajax({
                url: '<?php echo Mage::getUrl('camminopayment/token/zaaz'); ?>',
                header: {
                    'Content-Type': 'application/json',
                },
                type: 'POST',
                crossDomain: true,
                data: data,
                success: function(response) {
                    var responseJson = JSON.parse(response)
                    jQuery('#cammino_payment_cc_zaaz_access_token').val(responseJson.access_token);
                    jQuery('#cammino_payment_cc_zaaz_card_hash').val(responseJson.retorno.token);
                    if(responseJson.erros) {
                        console.log(responseJson.erros)
                    }
                }
            });
        } else {
            obj.ccToken = false;
            jQuery('#cammino_payment_cc_zaaz_access_token').val(null);
            jQuery('#cammino_payment_cc_zaaz_card_hash').val(null);
        }
    }

    function getCreditCardLabel(cardNumber) {
        var regexVisa = /^4[0-9]{12}(?:[0-9]{3})?/;
        var regexMaster = /^5[1-5][0-9]{14}/;
        var regexAmex = /^3[47][0-9]{13}/;
        var regexDiners = /^3(?:0[0-5]|[68][0-9])[0-9]{11}/;
        var regexDiscover = /^6(?:011|5[0-9]{2})[0-9]{12}/;
        var regexJCB = /^(?:2131|1800|35\d{3})\d{11}/;
        if (regexVisa.test(cardNumber)) {
            return 'visa';
        }
        if (regexMaster.test(cardNumber)) {
            return 'master';
        }
        if (regexAmex.test(cardNumber)) {
            return 'amex';
        }
        if (regexDiners.test(cardNumber)) {
            return 'diners';
        }
        if (regexDiscover.test(cardNumber)) {
            return 'discover';
        }
        if (regexJCB.test(cardNumber)) {
            return 'jcb';
        }
        return '';
    }

    if (jQuery('#cammino_payment_cc_cpf')) {
        jQuery('#cammino_payment_cc_cpf').mask('000.000.000-00');
    }

    if (jQuery('#cammino_payment_cc_cc_number')) {
        jQuery('#cammino_payment_cc_cc_number').mask('0000 0000 0000 0000');
    }
</script>